apiVersion: v1
kind: Service
metadata:
  name: staticserver
  labels:
    app: staticserver
spec:
  ports:
  - port: 80
    name: staticweb
  clusterIP: None
  selector:
    app: staticserver
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "staticserver"
  replicas: 2
  selector:
    matchLabels:
      app: staticserver
  template:
    metadata:
      labels:
        app: staticserver
    spec:
      containers:
      - name: staticserver
        image: staticserver
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/staticserver/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

